INCL = -I ../src/header
READNODE = read_node
READTREE = read_tree

readnode:
	g++ -g $(READNODE).cpp -o $(READNODE).exe $(INCL) ../src/src/*.cpp

readtree:
	g++ -g $(READTREE).cpp -o $(READTREE).exe $(INCL) ../src/src/*.cpp